# Generated by Django 4.2.4 on 2023-09-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=20)),
                ('carPrice', models.CharField(max_length=20)),
                ('carEngine', models.CharField(max_length=20)),
                ('fuel', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=15)),
                ('doors', models.IntegerField()),
                ('carImg', models.ImageField(upload_to='')),
                ('frontImg', models.ImageField(blank=True, upload_to='')),
                ('backImg', models.ImageField(blank=True, upload_to='')),
                ('sideImg', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
