# Generated by Django 4.2.4 on 2023-10-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=20)),
                ('carPrice', models.CharField(max_length=20)),
                ('carEngine', models.CharField(max_length=20)),
                ('fuel', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=15)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('doors', models.IntegerField()),
                ('carImg', models.ImageField(upload_to='')),
                ('carSdImg', models.ImageField(upload_to='')),
                ('carFrImg', models.ImageField(upload_to='')),
                ('carInImg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('sname', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
    ]
