# Generated by Django 4.2.4 on 2023-09-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='backImg',
        ),
        migrations.RemoveField(
            model_name='car',
            name='frontImg',
        ),
        migrations.RemoveField(
            model_name='car',
            name='sideImg',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
